spring.application.name=practice

notification.type = sms

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:file:C:/Users/Angikar/Documents/practiceDB/h2_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=arc
spring.datasource.password=arctest
spring.jpa.hibernate.ddl-auto=update
